### ISSUE TITLE
Cursor: pointer, suggestion

### ISSUE THREAD

**Issue by georgiamshaw** [fac-17/ABCD-week2-project#11]
Maybe you could add cursor: pointer to your buttons? Just so that the user is more aware that they can interact with them!

<img width="1440" alt="Screenshot 2019-07-12 at 10 11 02" src="https://user-images.githubusercontent.com/36238916/61116954-7e6e1b80-a48d-11e9-9304-70fb6cf2cc10.png">

**Comment by georgiamshaw** [comment]
Oooops the mouse didn't show up in the screenshot! But hopefully you know what I mean :)

**Comment by victormasson21** [comment]
Yes we do - we've added this feature, thank you!
