### ISSUE TITLE
Tests are Failing

### ISSUE THREAD

**Issue by RohanSSS** [fac-17/ABCD-week2-project#25]
your tests fail with the error

```
description: document.getElementsByName('description')[0].value,
                     ^

ReferenceError: document is not defined
    at Object.addTodo (/home/rss/Documents/Coding/FAC-Mentoring/ABCD-week2-project/logic.js:43:22)
```
This seems to be because you are accessing the dom from within your addTodo function. This makes it impossible to test addTodo without a renderer running within your tests.

You also want to avoid touching the dom within logic.js. Consider switching description to an argument, and simply getting its value in dom.js before you call the function. (Which you actually seem to be trying to do.)

try console logging `event.target` on line 68 of dom.js to see how you can find the correct value for description.

**Comment by victormasson21** [comment]
Cracked this and the tests now run fine, thanks for flagging!
