### ISSUE TITLE
code after return statement

### ISSUE THREAD

**Issue by RohanSSS** [fac-17/ABCD-week2-project#28]
Your deleteTodo functions has the lines
```
    var words = ['spray', 'limit', 'elite', 'exuberant', 'destruction', 'present'];
    const result = words.filter(word => word.length > 6);
```
after the return statement in the function.
You don't really want anything after a return statement in your code, cause the lines will never get run. So you should either move these to before or delete them if they are unnecessary.

**Comment by frannyfra** [comment]
Done it!!!Thanks Rohan !

ABCD team
